# Site settings
title: Institute for the Self
subtitle: 
email: lqb@alum.mit.edu
description: Change the world by changing yourself.
baseurl: "/productivity" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: Boston
state: MA
zip_code: 
country: United States of America
phone: 850.443.5020

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# Social settings
500px_url:
facebook_url: https://www.facebook.com/lqbii
github_url: https://github.com/lqb2/
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/lqb2
linkedin_url: https://www.linkedin.com/in/lawrencebarrinerii
pinterest_url: https://www.pinterest.com/lqb2/
slack_url:
twitter_url: https://twitter.com/lqb2

# Build settings
markdown: kramdown

sass:
  style: compressed
